apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-dev-project
  namespace: argocd
spec: 
  destination: 
    namespace: test-1
    server: "https://kubernetes.default.svc"
  #added project
  project: dev-project
  source: 
    path: guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

