apiVersion: v1
kind: Secret
metadata:
  name: repo-creds-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/prabinay
  password: //ssh key here
  username: my-token