apiVersion: v1
kind: Secret
metadata:
  name: private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git@github.com:prabinay/Agro-CD.git
  url: 
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
     # private key goes here
    -----END OPENSSH PRIVATE KEY----

    